version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - junit2otlp

  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:93a9885459c9406db8ac446f77f290b02542e8d5
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:13133/
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./build/tests.json:/tmp/tests.json
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "14317:4317"  # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - prometheus
    networks:
      - junit2otlp

networks:
  junit2otlp:
    driver: bridge
