receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug
  file:
    path: /tmp/tests.json

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, logging, zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, logging]
