name: Tests

on:
  push:
    branches:    
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Get dependencies
        run: |
          go get -u gotest.tools/gotestsum
          go get google.golang.org/grpc/internal/transport@v1.41.0
          go get google.golang.org/grpc@v1.41.0

      - name: Run Unit tests
        run: gotestsum --format short-verbose -- -timeout=5m ./...
